# Site settings
author: Nina Mortensen
title: 
header-img: img/home-bg.png
email: nina.mortensen@stern.nyu.edu
copyright_name: Nina Mortensen
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nm1874

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
